import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import 'flowbite';
import CartContext from "@/context/CartContext"
import  ViewedContext  from "@/context/ViewedContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <body className={inter.className}>

          <CartContext>
            <ViewedContext>
              <Navbar />
              {children}
              {/* <Footer /> */}
            </ViewedContext>
          </CartContext>

        </body>

      </html>
    </>
  );
}
